### ISSUE TITLE
Feature Request: Bake

### ISSUE THREAD

**Issue by webtop** [Svish/wsdl-viewer#1]
There needs to be some way to "bake" the output to a single HTML file. Right now, the WSDL needs to be parsed each time it's viewed.

Thanks

**Comment by Svish** [comment]
When I made this, the point was that it would always show the latest version from version control. And had to do it as simple as I could, so tried to avoid any sort of server-side caching and such...

But yeah, it could probably be useful if it had some sort of caching or "baking" feature. Could probably need some improvements on how it displays things too, but anyways, I'm unfortunately not able to do any work on this thing at the moment... 🙁

You're more than welcome to though, if you can. Just fork it and do whatever you want with it 😃
